FROM alpine:3.19.0 AS build

RUN apk update && \
    apk add --no-cache \
        build-base=0.5-r3 \
        cmake=3.27.8-r0 \
        boost1.82-dev=1.82.0-r3

COPY ./project_verificator_service /project_verificator_service

WORKDIR /project_verificator_service/build

RUN cmake -DCMAKE_BUILD_TYPE=Release .. && \
    cmake --build .

# RUN cmake -DCMAKE_BUILD_TYPE=Release .. && \
#     cmake --build . --parallel 8

FROM alpine:3.19.0

RUN apk update && \
    apk add --no-cache \
    libstdc++=13.2.1_git20231014-r0 \
    boost1.82-program_options=1.82.0-r3

RUN addgroup -S dev && adduser -S dev -G dev
USER dev

COPY --chown=dev:dev --from=build \
    ./project_verificator_service/build/p_v_service \
    ./app/

# ENTRYPOINT [ "./app/p_v_service", '"0:0:0:0"', '"8080"']
CMD ["./app/p_v_service", "0.0.0.0", "8080"]
EXPOSE 8080