version: '3.8'
services:
  comments-service:
    container_name: comments-service
    build:
      context: ./
      dockerfile: Dockerfile.comments-service
    restart: always
    ports:
      - "8080:8080"
    networks:
      - web

  scylla-node1:
    image: scylladb/scylla:5.2
    container_name: scylla-node1
    restart: always
    command: --seeds=scylla-node1 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - ./scylla/scylla-data:/var/lib/scylla
      - ./scylla/scylla-init.txt:/scylla-init.txt
    networks:
      - web
    healthcheck:
      test: ["CMD", "nodetool", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  web:
    driver: bridge
